<?php

namespace AshAllenDesign\ShortURL\Models\Factories;

use AshAllenDesign\ShortURL\Models\ShortURLVisit;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Carbon;

/**
 * @extends Factory<ShortURLVisit>
 */
class ShortURLVisitFactory extends Factory
{
    // combo of serbanghita/Mobile-Detect (MIT License) and jenssegers/agent (MIT License)
    private $browsers = [
        'Chrome',
        'Dolfin',
        'Opera',
        'Skyfire',
        'Edge',
        'IE',
        'Firefox',
        'Bolt',
        'TeaShark',
        'Blazer',
        'Safari',
        'WeChat',
        'UCBrowser',
        'baiduboxapp',
        'baidubrowser',
        'DiigoBrowser',
        'Mercury',
        'ObigoBrowser',
        'NetFront',
        'GenericBrowser',
        'PaleMoon',
        'Opera Mini',
        'Coc Coc',
        'Vivaldi',
        'Netscape',
        'Mozilla',
    ];
    // combo of serbanghita/Mobile-Detect (MIT License) and jenssegers/agent (MIT License)
    private $platforms = [
        'AndroidOS',
        'BlackBerryOS',
        'PalmOS',
        'SymbianOS',
        'WindowsMobileOS',
        'WindowsPhoneOS',
        'iOS',
        'iPadOS',
        'SailfishOS',
        'MeeGoOS',
        'MaemoOS',
        'JavaOS',
        'webOS',
        'badaOS',
        'BREWOS',
        'Windows',
        'Windows NT',
        'OS X',
        'Debian',
        'Ubuntu',
        'Macintosh',
        'OpenBSD',
        'Linux',
        'ChromeOS',
    ];
    // serbanghita/Mobile-Detect (MIT License)
    private $phoneDevices = [
        'iPhone',
        'BlackBerry',
        'Pixel',
        'HTC',
        'Nexus',
        'Dell',
        'Motorola',
        'Samsung',
        'LG',
        'Sony',
        'Asus',
        'Xiaomi',
        'NokiaLumia',
        'Micromax',
        'Palm',
        'Vertu',
        'Pantech',
        'Fly',
        'Wiko',
        'iMobile',
        'SimValley',
        'Wolfgang',
        'Alcatel',
        'Nintendo',
        'Amoi',
        'INQ',
        'OnePlus',
        'GenericPhone',
    ];
    // combo of serbanghita/Mobile-Detect (MIT License) and jenssegers/agent (MIT License)
    private $tabletDevices = [
        'iPad',
        'NexusTablet',
        'GoogleTablet',
        'SamsungTablet',
        'Kindle',
        'SurfaceTablet',
        'HPTablet',
        'AsusTablet',
        'BlackBerryTablet',
        'HTCtablet',
        'MotorolaTablet',
        'NookTablet',
        'AcerTablet',
        'ToshibaTablet',
        'LGTablet',
        'FujitsuTablet',
        'PrestigioTablet',
        'LenovoTablet',
        'DellTablet',
        'XiaomiTablet',
        'YarvikTablet',
        'MedionTablet',
        'ArnovaTablet',
        'IntensoTablet',
        'IRUTablet',
        'MegafonTablet',
        'EbodaTablet',
        'AllViewTablet',
        'ArchosTablet',
        'AinolTablet',
        'NokiaLumiaTablet',
        'SonyTablet',
        'PhilipsTablet',
        'CubeTablet',
        'CobyTablet',
        'MIDTablet',
        'MSITablet',
        'SMiTTablet',
        'RockChipTablet',
        'FlyTablet',
        'bqTablet',
        'HuaweiTablet',
        'NecTablet',
        'PantechTablet',
        'BronchoTablet',
        'VersusTablet',
        'ZyncTablet',
        'PositivoTablet',
        'NabiTablet',
        'KoboTablet',
        'DanewTablet',
        'TexetTablet',
        'PlaystationTablet',
        'TrekstorTablet',
        'PyleAudioTablet',
        'AdvanTablet',
        'DanyTechTablet',
        'GalapadTablet',
        'MicromaxTablet',
        'KarbonnTablet',
        'AllFineTablet',
        'PROSCANTablet',
        'YONESTablet',
        'ChangJiaTablet',
        'GUTablet',
        'PointOfViewTablet',
        'OvermaxTablet',
        'HCLTablet',
        'DPSTablet',
        'VistureTablet',
        'CrestaTablet',
        'MediatekTablet',
        'ConcordeTablet',
        'GoCleverTablet',
        'ModecomTablet',
        'VoninoTablet',
        'ECSTablet',
        'StorexTablet',
        'VodafoneTablet',
        'EssentielBTablet',
        'RossMoorTablet',
        'iMobileTablet',
        'TolinoTablet',
        'AudioSonicTablet',
        'AMPETablet',
        'SkkTablet',
        'TecnoTablet',
        'JXDTablet',
        'iJoyTablet',
        'FX2Tablet',
        'XoroTablet',
        'ViewsonicTablet',
        'VerizonTablet',
        'OdysTablet',
        'CaptivaTablet',
        'IconbitTablet',
        'TeclastTablet',
        'OndaTablet',
        'JaytechTablet',
        'BlaupunktTablet',
        'DigmaTablet',
        'EvolioTablet',
        'LavaTablet',
        'AocTablet',
        'MpmanTablet',
        'CelkonTablet',
        'WolderTablet',
        'MediacomTablet',
        'MiTablet',
        'NibiruTablet',
        'NexoTablet',
        'LeaderTablet',
        'UbislateTablet',
        'PocketBookTablet',
        'KocasoTablet',
        'HisenseTablet',
        'Hudl',
        'TelstraTablet',
        'GenericTablet',
    ];
    // jenssegers/agent (MIT License)
    private $desktopDevices = [
        'Macintosh',
    ];
    protected $model = ShortURLVisit::class;

    public function definition(): array
    {
        return [
            'ip_address' => $this->faker->ipv4(),
            'operating_system' => $this->faker->randomElement(
                $this->platforms,
            ),
            'operating_system_version' => $this->faker->randomFloat(8, 20),
            'browser' => $this->faker->randomElement($this->browsers),
            'browser_version' => $this->faker->userAgent(),
            'device_type' => $this->faker->randomElement(
                array_merge(
                    $this->phoneDevices,
                    $this->tabletDevices,
                    $this->desktopDevices,
                )),
            'visited_at' => Carbon::now(),
            'referer_url' => $this->faker->url(),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ];
    }
}
